[package]
name = "freeciv-savefile-viewer"
version = "0.1.0"
authors = ["W <git@worik.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.8.0"
xz2 = "0.1"
regex = "1.3.9"